<nav aria-label="Page navigation">
    <ul class="pagination pagination-lg">
        <!-- Pagination will be generated by JavaScript -->
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Loading">
                <span aria-hidden="true">...</span>
            </a>
        </li>
    </ul>
</nav>